#!/bin/sh

case "$1" in
start)
    # Ref : http://php.net/manual/en/features.commandline.webserver.php
    php -S HOST:PORT -t /path/to/website &
    echo $!>/var/run/simple_http_service.pid
    ;;
stop)
    kill `cat /var/run/simple_http_service.pid`
    rm /var/run/simple_http_service.pid
    ;;
restart)
    $0 stop
    $0 start
    ;;
status)
    if [ -e /var/run/simple_http_service.pid ]; then
       echo simple_http_service is running, pid=`cat /var/run/simple_http_service.pid`
    else
       echo simple_http_service is NOT running
       exit 1
    fi
    ;;
*)
    echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
