stages:
    - parallel

mdl:
    stage: parallel
    image: icehe/markdownlint
    script:
        - mdl --style markdown/lint/style.rb --list-rules
        - mdl --style markdown/lint/style.rb . --git-recurse && echo 'All is well.'
    allow_failure: true
        # `mdl` doesn't work as expect and i don't know why...

#pages:
#    # Deploy @ GitLab Pages ( Disabled )
#    stage: parallel
#    script:
#        # Build：temporary directory `.public/`
#        - mkdir .public
#        - cp -r * .public
#        # Release：formal directory `public/`
#        - mv .public public
#    artifacts:
#        paths:
#            - public
#    only:
#        - master
