image: ruby

before_script:
    - gem install mdl

stages:
    - parallel

md-lint:
    stage: parallel
    script:
        - mdl --style _ci/markdownlint.style.rb --list-rules
        - mdl --style _ci/markdownlint.style.rb --git-recurse . && echo ''

pages:
    stage: parallel
    script:
        # 生成：临时目录 .public
        - mkdir .public
        - cp -r * .public
        # 发布：发布目录 public
        - mv .public public
    artifacts:
        paths:
            - public
    only:
        - master
